### PR TITLE
558 delete xmltag/hotkeys

### LINKED ISSUE #557: Delete a special character
Make sure this respects position and still works against broken data sets. For a project with a broken data set, removing a character at position `3` should remove all characters at that position.  This will help heal the data and give the users a chance to get things back to normal.  If we only remove the first entry at the position, then the crap shoot for that position would simply continue.  Removing all connected broken data is the best thing to do.  These were broken anyway and the user was likely unable to use any of those characters anyway.  They are there in error.   

Ensure the mapping for this function is what it needs to be in web.xml

### LINKED ISSUE #558: Delete a XML entry
Make sure this respects position and still works against broken data sets. For a project with a broken data set, removing a XML entry at position `3` should remove all entries at that position.  This will help heal the data and give the users a chance to get things back to normal.  If we only remove the first entry at the position, then the crap shoot for that position would simply continue.  Removing all connected broken data is the best thing to do.  These were broken anyway and the user was likely unable to use any of those characters anyway.  They are there in error.   

Ensure the mapping for this function is what it needs to be in web.xml

### PR DESCRIPTION
**Pull request by cubap**
closes #558 
closes #557

Database cleaning done manually. Generally, removed all records at a position for a project and stopped changing every record whenever a delete is made. Gaps no longer break the display and self-mend on resorting updates anyway.

### CODE REVIEW

**Comment by cubap** [comment]
It works with buttons.jsp as written using the query string, which we can change outside of this.
```java
if (request.getParameter("deletetag") != null) {
                    int pos = Integer.parseInt(request.getParameter("position"));
                    TagButton b = new TagButton(projectID, pos, true);
                    b.deleteTag();
                }
```
using the tag by project

File: src/java/textdisplay/Hotkey.java [hunk 1]
```diff
@@ -449,69 +451,23 @@ public String keyhandler(int uid) {
...
-                        position++;
-                    } else {
-                        break;
-                    }
-                }
             } finally {
                 closeDBConnection(j);
-                closePreparedStatement(ps);
-                closePreparedStatement(update);
+                closePreparedStatement(ps);
```
Comment (thehabes) [inline src/java/textdisplay/Hotkey.java:470]: perfect

File: src/java/textdisplay/TagButton.java [hunk 2]
```diff
@@ -838,88 +842,46 @@ public void removeButtonsByProject(int projectID) throws SQLException {
...
+               ps = j.prepareStatement(query);
+               ps.setString(1, desc);
+               ps.setInt(2, projectID);
+               ps.setInt(3, position);
+               ps.execute();
+           } finally {
+               closeDBConnection(j);
+               closePreparedStatement(ps);
+           }
+       }
```
Comment (thehabes) [inline src/java/textdisplay/TagButton.java:860]: Much more sane

**Review by thehabes — APPROVED** [review]
